query TrackProyectos($usuario_id: ID!) {
  usuario(usuario_id: $usuario_id) {
    usuario_id
    proyectos_contribuidos {
      descripcion
      estado
      fecha_limite_implementacion
      fecha_limite_recaudacion
      fecha_registro
      localidad_id
      meta_recaudacion
      nombre
      proyecto_id
      saldo
      usuario_administrador_id
    }
  }
}
